In [4]:
import pandas as pd
import numpy as np

In [5]:
pd.options.display.float_format = '{:,.2f}'.format

### Problema 1
Vamos praticar gerar matrizes e fazer operações com as linhas e colunas:

(a) Crie uma matriz A com as dimensões (5, 4) e elementos aleatórios variando entre 0 e 50, com o 50 incluso;

__Dica:__ Utilize as funções `np.random.randint` e `np.reshape`

(b) Retorne a média do vetor

(c) Retorne os menores valores de cada coluna;

(d) Retorne os maiores valores de cada linha.

In [28]:
# a
mat1 = np.random.randint(0, 50, 20).reshape(5,4)
mat1

array([[20,  9, 27, 31],
       [35, 43, 21, 34],
       [ 6,  6, 33, 43],
       [13, 29,  9, 34],
       [32, 27, 28, 16]])

In [29]:
# b
mat1.mean()

24.8

In [32]:
# c
mat1.min(axis = 0)

array([ 6,  6,  9, 16])

In [33]:
# d
mat1.min(axis = 1)

array([ 9, 21,  6,  9, 16])

### Problema 2

Crie um objeto DataFrame que contenha os dados da tabela abaixo, os quais se referem ao peso, altura e idade de cinco pessoas:


| Peso (kg) | Altura (cm) | Idade (anos) |
|-----------|-------------|--------------|
|  47 | 161	| 31 |
|  80 | 170	| 21 |
|  60 | 175	| 16 |
|  90 | 162	| 28 |
| 100 | 185	| 23 |
| 147 | 189 | 32 |

Com base no DataFrame criado, realize o que for pedido nos itens abaixo:

(a) Visualize apenas os dados da coluna que contém a altura das pessoas;

(b) Obtenha a idade média das pessoas;

(c) Obtenha os dados das pessoas que estão abaixo da altura média;

(d) Crie um nova coluna no DataFrame que contenha o IMC (Índice de Massa Corporal) de cada pessoa;

__Obs.:__ A fórmula para o IMC é dada por IMC = Peso/(Altura)² com o peso em kg e a altura em metros.

(e) Remova a coluna que contém a idade das pessoas;

(f) Crie uma nova coluna chamada Classificação, que contenha a classificação de cada indivíduo, de acordo com o seu IMC. Para isso, consulte a tabela abaixo.

| IMC             | Classificação |
|-----------------|---------------|
Menor que 18,5    | Subpeso |
Entre 18,5 e 24,9 | Normal |
Entre 25,0 e 29,9 | Sobrepeso |
Entre 30,0 e 39,9 | Obesidade Grau I |
Maior que 40,0    | Obesidade Grau II |

(g) Salve esses dados do DataFrame em um arquivo csv.

In [38]:
df = pd.read_clipboard() #Copiei o quadro acima

In [39]:
df

Peso (kg)  Altura (cm)  Idade (anos)
0         47          161            31
1         80          170            21
2         60          175            16
3         90          162            28
4        100          185            23
5        147          189            32

In [ ]:
df

### Problema 3

O arquivo avocado.xlsx consiste em um dataset que contém dados sobre vendas de abacates  em diversas regiões dos Estados Unidos. Essa dataset contém as seguintes colunas:

| Coluna | Descrição |
|--------|-----------|
| Date | data da observação |
| AveragePrice | preço médio de um único abacate |
| year | ano |
| region | cidade ou região da observação |
| Total Volume | volume total de abacates vendidos |

Além das informações acima, contidas no arquivo avocado.xlsx, o tipo do abacate (convencional ou orgânico) também seria uma informação importante para a sua análise. Suponhamos que você conseguiu essas informações para cada uma das observações do arquivo avocado.csv, na mesma ordem, e salvou-as no arquivo avocado_type.xlsx. Portanto, tudo o que você precisa é juntar esses dois arquivos em um mesmo DataFrame.

Com o DataFrame criado, obtenha o que é solicitado nos itens elencados abaixo:




(a) A quantidade de abacates do tipo convecional e do tipo orgânico.


(b) A quantidade de registros (linhas) de abacates vendidos para cada região ordenada da maior venda para a menor.

(c) Para que todos os labels das colunas fiquem padronizados, renomeie aqueles que estão iniciando em letra minúscula para que iniciem em letra maiúscula, trocando espaço por _ e adicionando _ como separação de texto.

(d) Essa dado possui duplicados? Se sim, remova-os do dataset.

(e) Retire dos dados a região 'TotalUS'

(g) Apresente as regiões que mais venderam abacate em todo o período em ordem decrescente.

(h) Calcule o volume total de abacates vendidos para cada tipo e ano.

(f) existe alguma região que foi a maior responsável pela queda na produção de 2018?

(g) Qual cidade menos faturou com a venda de abacates?

### Problema 4

Com base no dataset 'Video_Games_Sales.csv' responda:



(a) Quantos jogos existem em cada genero?


(b) Temos duplicados nesses dados? E nulos?

(b) Quantos jogos de cada publisher receberam nota acima de 9 na avaliação dos usuarios?


(c) Faça uma tabela que mostre o total vendido por ano por pais/globalmente de cada publisher? Você consegue observar algum padrão? Com se comportaram as vendas na América do Norte (NA) ao longo do tempo? O mesmo foi visto nos demais lugares? 



(d) Qual foi jogo mais vendido na união européia? De que ano ele é e qual a editora?



(e) Quantos % os generos ['Racing', 'Sports', 'Shooter'] representam na base de dados? 

(f) Qual plataforma vendeu menos globalmente? obs: imprimir somente o nome

### Problema 5
A pasta 'data/datasus' contém informações sobre casos de dengue e tabelas auxiliares. <br>

| Tabela | Conteúdo |
|--------|----------|
| Dengue | Quantidade de casos por município |
| Agua | Quantidade de residências em cada município por tipo o abastecimento de água |
| InstalacoesSanitarias | Quantidade de residências em cada município por tipo de rede de esgoto |
| Pib | PIB per capita de cada município |
| Municipios | Relaciona o id_municipio com seu nome e estado |
| Populacao | Quantidade de pessoas morando em áreas urbanas, rurais e população total por município |
| Sexo | Quantidade de pessoas por sexo em cada município |

(a) Calcular o número de casos de dengue por cada estado apresentando os dados em ordem decrescente.


In [65]:
import os
os.getcwd()
folder = './data/datasus/'
files = os.listdir(folder)
print(files)
df_agua = pd.read_csv(folder + files[0], delimiter = ',')
df_cid10 = pd.read_csv(folder + files[1], delimiter = ',')
df_den = pd.read_csv(folder + files[2], delimiter = ',')
df_inst_san = pd.read_csv(folder + files[3], delimiter = ',')
df_mun = pd.read_csv(folder + files[4], delimiter = ',')
df_pib = pd.read_csv(folder + files[5], delimiter = ',')
df_pop = pd.read_csv(folder + files[6], delimiter = ',')
df_sexo = pd.read_csv(folder + files[7], delimiter = ',')

['Agua.csv', 'Cid10.csv', 'Dengue.csv', 'InstalacoesSanitarias.csv', 'Municipios.csv', 'Pib.csv', 'Populacao.csv', 'Sexo.csv']


In [86]:
df_mun.merge(df_den, how = 'left', on = 'id_municipio')['UF'].value_counts().sort_values(ascending = False)

MG    853
SP    645
RS    497
BA    417
PR    399
SC    295
GO    246
PI    224
PB    223
MA    217
PE    185
CE    184
RN    167
PA    144
MT    141
TO    139
AL    102
RJ     92
MS     79
ES     78
SE     75
AM     62
RO     52
AC     22
AP     16
RR     15
DF      1
Name: UF, dtype: int64

(b) Utilizando o dataset InstalacoesSanitarias.csv, determine o número de pessoas que não possuem meio sanitário algum de descarte de dejetos por estado.

In [89]:
df_mun.merge(df_inst_san, how = 'left', on = 'id_municipio').groupby('UF')['nao_possui'].sum().sort_values(ascending = False)

UF
GO   5,814,249.00
BA   1,201,606.00
MA     946,217.00
PI     649,878.00
CE     645,246.00
PE     478,587.00
PA     306,028.00
MG     268,622.00
PB     217,920.00
AL     212,043.00
AM     211,491.00
TO     115,376.00
AC      73,437.00
RS      65,817.00
SE      62,352.00
RN      62,137.00
MT      52,961.00
PR      33,131.00
RR      29,705.00
SP      23,768.00
RO      22,181.00
RJ      16,987.00
SC      16,219.00
ES      13,060.00
AP      11,208.00
MS       9,010.00
DF           0.00
Name: nao_possui, dtype: float64

(c) Crie uma coluna com a posição de ranking considerando o PIB. Os maiores PIB devem ter os menores valores de ranking.

In [103]:
df_pib.sort_values(by = 'pib_percapta', ascending = False, inplace = True)
df_pib.reset_index(inplace = True)
df_pib['ranking_PIB'] = df_pib.index + 1
df_pib

index  id_registro  id_municipio  pib_percapta  ranking_PIB
0      3152         3153          3155    715,193.70            1
1      2962         2963          2965    340,688.49            2
2      3574         3575          3577    278,145.26            3
3      3230         3231          3233    255,658.30            4
4      5163         5164          5169    254,242.69            5
...     ...          ...           ...           ...          ...
5554    617          618           618      3,566.34         5555
5555   2106         2107          2109      3,561.71         5556
5556    563          564           564      3,529.10         5557
5557    643          644           644      3,510.69         5558
5558    572          573           573      3,241.29         5559

[5559 rows x 5 columns]

(d) Qual o PIB dos 5 municípios com mais casos de dengue e sua posição no ranking?

In [141]:
df_pop.head()

id_registro  id_municipio  urbana     rural  total
0            1             1   13806 10,248.00  24054
1            2             2    3622  9,136.00  12758
2            3             3    8185  8,913.00  17098
3            4             4    8755  7,922.00  16677
4            5             5   75906 13,729.00  89635

In [147]:
df1 = df_mun.merge(df_pib, how = 'left', on = 'id_municipio')
df2 = df1.merge(df_den, how = 'left', on = 'id_municipio')
df3 = df2.merge(df_pop, how = 'left', on = 'id_municipio')
df3 = df3.loc[:,['id_municipio', 'municipio', 'casos', 'ranking_PIB','pib_percapta', 'total']]
df3['pib_municipio'] = df3['pib_percapta']*df3['total']
df3.sort_values(by = 'casos', ascending = False, inplace = True)
df3.head()

id_municipio                   municipio      casos  ranking_PIB  \
5565          5566           522200 Vianópolis 239,395.00       905.00   
5336          5337  520085 Americano do Brasil  10,859.00     1,572.00   
5412          5413              520810 Formoso   9,340.00       742.00   
948            949            230435 Forquilha   4,321.00     1,602.00   
5214          5215              510325 Colniza   3,298.00       641.00   

      pib_percapta     total  pib_municipio  
5565     26,445.72 12,476.00 329,936,802.72  
5336     19,774.03  5,488.00 108,519,876.64  
5412     29,034.21  4,848.00 140,757,850.08  
948      19,494.40 21,736.00 423,730,278.40  
5214     31,016.19 25,913.00 803,722,531.47